### ISSUE TITLE
Error: Unexpected value 'Ng2DragDropModule' imported by the module

### ISSUE THREAD

**Issue by gund** [ObaidUrRehman/ng2-drag-drop#1]
Trying to use it angular2 app generated by angular cli. Default setup (with webpack).
Installed module via npm and trying to import to my app module:
`imports: [Ng2DragDropModule]`

Everything compiles fine but in browser I got:
`Error: Unexpected value 'Ng2DragDropModule' imported by the module 'AppModule'`

Importing module like so:
`import { Ng2DragDropModule } from 'ng2-drag-drop'`

Do you know what it can be?

Thanks for the module btw =)

**Comment by gund** [comment]
Also if I console Ng2DragDropModule just before `@NgModule` annotation I can see:
```ts
function Ng2DragDropModule() {}
```

**Comment by ObaidUrRehman** [comment]
@gund , I think this is probably related to using webpack. I haven't tested or added support for webpack yet. (I plan to). If could possibly provide me a plunkr that would really help.

**Comment by gund** [comment]
@ObaidUrRehman I'm not sure it is possible to use webpack with plunkr =)

Anyway there is really no configuration required for webpack to use your library, I just npm install it and import that should do the job.
But for some reason angular complains.

You can try to create project with angular cli, install your lib and import it to AppModule to see that error in runtime.

**Comment by ObaidUrRehman** [comment]
@gund what version of ng-cli are you using? Its seems that this is a know problem with older versions of cli. See Also: https://github.com/videogular/videogular2/issues/249

I encountered the same problem with angular-cli 1.0.0-beta-15.0.0 but with v 1.0.0-beta.19-3 its working fine.

**Comment by gund** [comment]
I do use angular-cli v1.0.0-beta-16 so I will try to upgrade it and try again.
Thanks for referencing an issue.

**Comment by gund** [comment]
You are right with updated angular-cli (1.0.0-beta.19-3) this is not longer an issue.

Thanks a lot!

**Comment by sarora2073** [comment]
fyi - i'm having the same error, using the latest greatest angular-cli (1.0.0-beta.24) with angular 2.3.0. i happen to be using webpack, so not sure if that is a factor after all as suggested above.

**Comment by gund** [comment]
@sarora2073 can you tell if you are getting that error in AOT mode only?

**Comment by sarora2073** [comment]
No, i'm not doing this in AOT mode.

**Comment by ObaidUrRehman** [comment]
This seems to be an issue with angular-cli.
For refrence: https://github.com/angular/angular-cli/issues/3426

I need to look into this in detail.

**Comment by ObaidUrRehman** [comment]
@sarora2073 I just updated ng2-drag-drop to v0.5.1. Now using ngc to build instead of tsc (among other changes). Its now working on angular-cli v1.0.0-beta.24
