### ISSUE TITLE
Drag drop not working on any mobile browser

### ISSUE THREAD

**Issue by AmitBisht14** [ObaidUrRehman/ng2-drag-drop#101]
Have deployed the application on below URL:
http://ec2-18-220-151-90.us-east-2.compute.amazonaws.com/

It is working fine in desktop browser but not it is not working on any mobile browser, or Windows 10 touch device. You can check this in gameplay section from above url.

Also if you check the provided plunker demo that is also not working with mobile device

**Comment by ObaidUrRehman** [comment]
@AmitBisht14, this is a limitation. The Html drag drop Api does not work on Touch.
See this: https://github.com/ObaidUrRehman/ng2-drag-drop/issues/47#issuecomment-302653094
