### ISSUE TITLE
Angular 1.x

### ISSUE THREAD

**Issue by khullah** [ObaidUrRehman/ng2-drag-drop#2]
Hi, awesome directives! Any chances this is available to Angular 1.x versions too?

I'm a total noob in Angular 2, don't even know if there is something that restricts that, or if its easy like rendering typescript to javascript, then making some basic changes.

Thanks

**Comment by ObaidUrRehman** [comment]
@khullah you can check out a couple of excellent angularjs based solutions. I'd recommend this one: http://codef0rmer.github.io/angular-dragdrop/#!/.

**Comment by khullah** [comment]
Yeah, didn't really liked that one.. Tried some others, but no quite what I want.

I'll see if I can 'translate' yours to 1.x, if that's ok with you.

**Comment by ObaidUrRehman** [comment]
@khullah sure go ahead. No issues what so ever. This tutorial on native Html5 drag drop will help you get started: https://www.html5rocks.com/en/tutorials/dnd/basics/
