### ISSUE TITLE
Feature: Add custom dragHelper functionality

### ISSUE THREAD

**Issue by ObaidUrRehman** [ObaidUrRehman/ng2-drag-drop#22]
The `draggable` directive should take a `dragHelper` input that should be a `TemplateRef`. One should be able to define this in the markup:
    
    <div #myHelper>I am a custom DragHelper</div>

and be able to use it as custom dragHelper. We should also add a default `dragHandler` that should be a clone of the element since the current one sometimes becomes too transparent to provide a good visual feedback.

**Comment by jiann4321** [comment]
Need this functionality as well. Thanks!

**Comment by ObaidUrRehman** [comment]
In v 1.5.0 Added `dragImage` input to the `draggable` directive that takes image Url that is set when the item is being dragged. Later will expand this to custom elements. Closing this for now.
