### ISSUE TITLE
Compilation Error in AOT build.

### ISSUE THREAD

**Issue by shamim4063** [ObaidUrRehman/ng2-drag-drop#24]
## Drag and Drop run and work correctly with JIT compilation But Its through following error in AOT compilation.   

Error: Error encountered resolving symbol values statically. Reference to a local (non-exported) symbol 'Ng2DragDropModule'. Consider exporting the symbol (position 21:14 in the original .ts file), resolving symbol Ng2DragDropModule in /home/shamim/Boi2/boibazar/node_modules/ng2-drag-drop/src/ng2-drag-drop.module.d.ts, resolving symbol Ng2DragDropModule in /home/shamim/Boi2/boibazar/node_modules/ng2-drag-drop/index.d.ts, resolving symbol PublicPageModule in /home/shamim/Boi2/boibazar/src/app/pages/public-page/public-page.module.ts, resolving symbol PublicPageModule in /home/shamim/Boi2/boibazar/src/app/pages/public-page/public-page.module.ts

**OS: Ubuntu 16.04,
Node version : 6.9.5,
NPM: 3.10.10.
Angular version: 2.4.7**

**Comment by nidhinmoh** [comment]
hello,

I am also facing the same issue, can anyone help me with this thank you..

**Comment by ObaidUrRehman** [comment]
This is in progress but i am open to PRs as well.

**Comment by Vinutha-BK** [comment]
I am getting same error in  JIT compilation also, after upgrading to angular v4.0.0

**Comment by miczed** [comment]
I am having the same issue with ng2-drag-drop `1.2.0` and angular-cli `1.0.0-beta.32.3`. Is there any hotfix we can do ourselves while we wait for a release?

**Comment by ObaidUrRehman** [comment]
This is still a WIP.

**Comment by ObaidUrRehman** [comment]
Added AOT support in v1.3.0.
