### ISSUE TITLE
dragOverClass assigned to non valid drop targets

### ISSUE THREAD

**Issue by GerritK** [ObaidUrRehman/ng2-drag-drop#28]
If I assign the `dragOverClass` to a draggable (and droppable) element it gets the class assigned at drag start and short after again removed. The draggable helper has now the `dragOverClass` style.

**Comment by ObaidUrRehman** [comment]
@GerritK not sure if I understand. Can you show me a Plunkr demonstrating the issue?

**Comment by GerritK** [comment]
http://plnkr.co/edit/xHKXxXwiH4YzMzSE9xtF?p=preview

If you start dragging one of the items, it gets the `dragOverClass` assigned.
