### ISSUE TITLE
I need to move the component(Example: button component) into the droppable item.

### ISSUE THREAD

**Issue by partha006** [ObaidUrRehman/ng2-drag-drop#3]
My aim is to move the component(any component) from draggable to droppable. Is there default component which do that stuff?

**Comment by ObaidUrRehman** [comment]
@partha006 you can use this the `draggable` and `droppable` directives to achieve this. Please see: https://github.com/ObaidUrRehman/ng2-drag-drop/blob/master/README.md#use-the-draggable--droppable-directives.

Closing this as its more of a support ticket.
