### ISSUE TITLE
Error compiling with angular version 4

### ISSUE THREAD

**Issue by filipefreitas82** [ObaidUrRehman/ng2-drag-drop#38]
I'm getting this error after importing the module:

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule`

Using angular4.0.0 with angular cli 1.0.0

**Comment by ObaidUrRehman** [comment]
Fixed in v1.4.0
