### ISSUE TITLE
How to know in which array dropped?

### ISSUE THREAD

**Issue by kjiang99** [ObaidUrRehman/ng2-drag-drop#39]
I'm writing a dorm mgmt website using ang2.  It will show couple of rooms of a building on the right panel, and students on the left.   When I drag a student over to one of the rooms, how can I know which room it's dropped. 

This drag and drop api is awesome, but it seems to need to know the array name of the droppable.  What if the droppable belongs to a parent array.  How can I know which room dropped?

Thanks,
Kevin

**Comment by ObaidUrRehman** [comment]
In your case, the individual rooms would each be a `droppable`. Something like this:
```
<div droppable *ngFor="let room of rooms" (onDrop)="onItemDrop($event, room)">
   {{room.name}}
</div>
```
Notice how I have passed both the `$event` and the `room`  to the `onDrop` handler.

The student would be `draggable` with some `dragData`:
```
<div draggable [dragData]="student" *ngFor="let student of students">
   {{student.name}}
</div>
```
Now when you drop a student over the room you'll have the data on the `onDrop` event of the droppable:

```
onItemDrop(e: any, room) {
        //  e.dragData is the student & room is the one where it was dropped.      
    }
```

**Comment by kjiang99** [comment]
Perfect!!!  It works!!! Thanks a lot

**Comment by kjiang99** [comment]
I want to share what I did in demo:  http://dorm2.azurewebsites.net/AcadSession/1
I haven't done user mgmt, so it may interfere if mutliple people test at same time.

Click on the dorm such as 1st Floor Female at top.   The dorm rooms will show.

On the left panel is accordion menu.  Don't worry about Chinese.  Basically category by grade and class.

The students with name like (F): female, (B): Boarding student, [107F]: assigned to 107F room.
