### ISSUE TITLE
Can we disable any droppable container

### ISSUE THREAD

**Issue by rrohitesh** [ObaidUrRehman/ng2-drag-drop#41]
Hello All,

Can we have an option to disable to non-selected droppable container. Let's say we have two droppable container and i want to allow drop only on the selected container. The other container which is not selected i want to disable the drop functionality.

**Comment by ObaidUrRehman** [comment]
Your use case calls for a `droppable.disabled` property which when set to `false` disallows drops even for valid scopes.

**Comment by rrohitesh** [comment]
U mean like this: 

<div class="floor-selected" droppable.disabled = "false" [dragOverClass]="'drag-target-border-green-campus'" [dropScope]="'zone'"                    
           (onDrop)="onRoomSelected($event)">

</div>

**Comment by ObaidUrRehman** [comment]
More like this:

`<div class="floor-selected" droppable 
[disabled] = "true" 
[dragOverClass]="'drag-target-border-green-campus'" 
[dropScope]="'zone'" (onDrop)="onRoomSelected($event)">`

**Comment by rrohitesh** [comment]
Tried this but getting this exception :Can't bind to 'disabled' since it isn't a known property of 'div'.

**Comment by ObaidUrRehman** [comment]
@rrohitesh I'll add this property in the next release.

**Comment by rrohitesh** [comment]
many thanks. But, as of now there is no way to disable it? Because, already i have implemented this and at this point only i am facing challenge.

**Comment by ObaidUrRehman** [comment]
Added in v1.5.0
