### ISSUE TITLE
CSS is not working in large display screen

### ISSUE THREAD

**Issue by rrohitesh** [ObaidUrRehman/ng2-drag-drop#45]
Hi Obaid,

I found the when we are trying to drag the element then the dashed box will be visible around the dragged element also we can see the element shadow which is dragged. 

But, i large display its not working only the box is visible artificially. I don't know whether this is a bug or not but i found it is happening in the plunker example also.

**Comment by ObaidUrRehman** [comment]
Possible clone of #44.
