### ISSUE TITLE
Demo is using angular2.4.0, not angular4.0.0

### ISSUE THREAD

**Issue by idoor88** [ObaidUrRehman/ng2-drag-drop#59]
I am new to Angular, the ng2-drag-drop is using angular 4.0.0, but the demo is using angular 2.4.0, would you please upgrade the demo to angular 4.0.0? 

Also another newbie question, after I build the ng2-drag-drop, how do I use it in a separate angular project? like in java, I can build something into a jar file, then I can drop the jar file to a separate project and import it there, how does it work for ng2-drag-drop? what file is generated for me to import from a separate project?

Thanks

**Comment by ObaidUrRehman** [comment]
@idoor88 this component works in both angular 2 & 4. I'll update the demo to 4.0.0 soon.

I am not sure I quite understand the second part of your question but you can can't use this in Java.

**Comment by idoor88** [comment]
I meant after I build ng2-drag-drop, do I get a library file, which I can include in my own angular web project? 
Thanks

**Comment by idoor88** [comment]
Got it.
