### ISSUE TITLE
Error: Template parse errors: 'drag-helper' is not a known element:

### ISSUE THREAD

**Issue by idoor88** [ObaidUrRehman/ng2-drag-drop#60]
Hi all,
I am trying to use ng2-drag-drop in my angular 4 project, I copied the whole folder of drag-help of the demo project to my project and added <drag-helper></drag-helper> to my app.component.html, drag-helper.component.ts has selector: 'drag-helper', but after I build and start ng server, in my browser, I got this error:

Error: Template parse errors:
'drag-helper' is not a known element:
1. If 'drag-helper' is an Angular component, then verify that it is part of this module.
2. If 'drag-helper' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 

Any clue?
Thanks

**Comment by idoor88** [comment]
Got it working, sorry to bother.
Thanks

**Comment by gligoran** [comment]
@idoor88 You could have said how you got it to work.
