### ISSUE TITLE
'draggable' doesn't disable

### ISSUE THREAD

**Issue by fmjnax** [ObaidUrRehman/ng2-drag-drop#65]
I have a draggable div (that is actually images)

     <div draggable *ngFor="let card of player.cardHand" [dragData]="card" class="drag-div">
       <img src="{{cardBluePath + card.fileName}}" class="dragged">
     </div>

They can be dropped on to any of 9 available div's (slots), which populates the droppedItems list (and uses a pipe to filter the object based on the slot

            <div class="slot2" id="slot2" droppable (onDrop)="onItemDrop($event, '2')">
              <div class="panel-body">
                <div *ngFor="let card of droppedItems | slotFilter:{slot:'2'}" class="list-group-item">
                  <img src="{{cardBluePath + card.fileName}}"><br>
                </div>
              </div>
            </div>

Once an item is dropped onto a slot, I don't want it to be draggable again. Once it's there, it needs to stay there. Reading the documentation, I thought I needed to set the [draggable] to false, so I did this:

            <div class="slot1" id="slot1" droppable (onDrop)="onItemDrop($event, '1')" [draggable]="false">
              <div class="panel-body" [draggable]="false">
                <div [draggable]="false" *ngFor="let card of droppedItems | slotFilter:{slot:'1'}" class="slot">
                  <img src="{{cardBluePath + card.fileName}}" class="dropped" [draggable]="false"><br>
                </div>
              </div>
            </div>

However, the image is still being allowed to be dragged and inspecting the elements, the draggable tag is still = true, even though I am explicitly setting it to false on every element in the block.

Is this an issue, or am I doing something wrong?

**Comment by boldwade** [comment]
It would be nice if the draggable host property was configurable instead of always being set to 'true'.
Would you consider the following instead of the current 'Host' binding defined in the @directive annotation:
@HostBinding('draggable') @Input() isDraggable: boolean;

**Comment by ObaidUrRehman** [comment]
@fmjnax there is no `[draggable]=false` input to the draggable. Instead there is a `[dragEnabled]` property that must be set.
@boldwade thanks for your input. I've made that change.
