### ISSUE TITLE
drag and drop in multiple component 

### ISSUE THREAD

**Issue by therahuls1ngh** [ObaidUrRehman/ng2-drag-drop#7]
I have two component for example 
one.ts 
tasks[]
tasks ={"A","B"}
two.ts
tasks[]
when I drop one element i.e A from one.ts to two.ts  it should remove from one.ts and vice versa.

**Comment by ObaidUrRehman** [comment]
@therahuls1ngh you will have to manually remove/add the items. You will also need to apply both `droppable` and `draggable` directives on elements. This is something that is currently buggy. See #13

**Comment by ObaidUrRehman** [comment]
@therahuls1ngh Please see the updated plunkr demo. I have added a new example where you can drag and drop items between 2 list.

**Comment by vkadi-tcs** [comment]
Above plnkr link is not loading properly,
Can any one tell me how to implement multiple selection drag and drop using **"ng2-drag-drop"**

**Comment by ObaidUrRehman** [comment]
@vkadi-tcs that's an old plunker. See the latest one: http://plnkr.co/edit/2bjGgzWnbFrciEiCKLew?p=preview
Multiple selection drag drop feature is under consideration.
