### ISSUE TITLE
Plunker has no items

### ISSUE THREAD

**Issue by GiselleSerate** [ObaidUrRehman/ng2-drag-drop#73]
I'm trying to use your Plunker demo and there are no items populated to drag or drop. I've tried this on multiple browsers (Chrome, Safari) and it doesn't seem that it works on any of them. The code seems to indicate that, for example, the vegetable array exists and is trying to populate into the first draggable field. However, even when I put extra dummy text into the li element, no elements display, seeming to indicate that there is nothing in vegetables. 
The display looks like this: 
![screen shot 2017-07-31 at 10 41 57 am](https://user-images.githubusercontent.com/13649793/28790181-e97a2ed2-75dc-11e7-8763-e8e2ce2cc0f1.png)

**Comment by ObaidUrRehman** [comment]
The demo was out of date. This has been fixed.
Thanks for reporting.

http://plnkr.co/edit/2bjGgzWnbFrciEiCKLew?p=preview
