### ISSUE TITLE
Drag drop not supported in all browsers

### ISSUE THREAD

**Issue by Vinutha-BK** [ObaidUrRehman/ng2-drag-drop#8]
Currently I have implemented DnD by importing 'Ng2DragDropModule', its working fine in chrome and mozilla.
But not supported in safari and ms edge browser.
Please guide where we have to change to support all browsers.

**Comment by ObaidUrRehman** [comment]
@Vinutha-BK can you please let me know which version of Safari is causing issues. I have checked it against Safari v9.1.2 and it is working fine. There seems to be issues with Edge browser that I am looking into.

**Comment by Vinutha-BK** [comment]
@ObaidUrRehman Thank you for the quick response.I was checking with Safari v5.1.7 which is the latest version for windows 8 and its not working. Kindly suggest to resolve the issue in Edge browser.

**Comment by ersurajnegi** [comment]
DnD not working for EDGe browser

**Comment by ObaidUrRehman** [comment]
Will fix the issue in edge. Its because of using non-standard `content-type` in `dataTransfer.setData()`. Edge only accepts text or json.

@Vinutha-BK the Safari for windows is very old, apple dropped support for it ages ago.
