### ISSUE TITLE
Different CSS to the draggable element while in transit

### ISSUE THREAD

**Issue by calebeaires** [ObaidUrRehman/ng2-drag-drop#87]
[x] feature request

On some apps we use dragging to transform an element into another. dragClass apply CSS to the element that is being dragglabe and the element in transit. It would be great if whe could apply CSS to both separately. On this way, the css in the element dragabled is different from the element in transit.

**Comment by ObaidUrRehman** [comment]
@calebeaires the implementation is Kludgy at best. There may be side effects to this so I'll need feedback from you on this. There is a new input to the `draggable` directive called `dragTransitClass`.

**Comment by ObaidUrRehman** [comment]
Added in v2.7.0

**Comment by calebeaires** [comment]
@ObaidUrRehman thanks for everthing! now the only thing I am waiting for is the sort feature!
