### ISSUE TITLE
Drag handle intermittently not working

### ISSUE THREAD

**Issue by Sypher1987** [ObaidUrRehman/ng2-drag-drop#89]
I have come across an issue with the drag handles, because the current target that is used for the drag handles is updated on mouseover and the drag start requires movement of the mouse to initiate sometimes it does not work. The tracked current target can get updated when the mouse moves off the drag handle before the drag star event fires. This can be seen on the plunkr demo if you click and drag quickly using the drag handle.

I have made a fix in my fork of the project and issued a pull request  (#88).

**Comment by ObaidUrRehman** [comment]
Fixed in v2.7.0
