### ISSUE TITLE
Lowest version of Angular

### ISSUE THREAD

**Issue by Azayzel** [ObaidUrRehman/ng2-drag-drop#90]
What is the lowest version of Angukar that is supported? I seem to be getting "Object doesn't support property or method 'map'". I've been trying to hunt this down with no luck. This package works perfect on my Angular 4 app but not my Angular 2. Any ideas?

**Comment by Azayzel** [comment]
Found my answer

**Comment by Azayzel** [comment]
Re-opening to track "map" issue.

**Comment by ObaidUrRehman** [comment]
@Azayzel I haven't used [.map()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) anywhere in the source (only in the demo). Can you possibly provide the stack trace of the error. Btw, whats the exact version of Angular 2 that you are using.

Theoretically, this component works with Angular 2.0.0 but after recent changes, I need to test & validate this.

**Comment by Azayzel** [comment]
I am using 2.4.3 right now. But, oddly enough it seems to be an issue with ng2-drag-drop. When I exclude that module the program starts up just fine. Closing this and going to look into issue with that package.
