### ISSUE TITLE
Drag a single element multiple times

### ISSUE THREAD

**Issue by Gab-Metzger-Melpia** [ObaidUrRehman/ng2-drag-drop#91]
Hi guys, just wondering if it's possible to drag one element multiple times in different drop zones ?
I'm trying to build a bucketing system with a list of elements and multiple buckets. And I have an option with the possibility to add an element in multiple bucket. To do so I need the element not being deleted from the list when dropped on a bucket.

By the way, awesome library, thanks!! 😃

**Comment by ObaidUrRehman** [comment]
Yes, this is possible. Its completely up to you if you want to remove the item from the drag source list or not. ng2-drag-drop does not manage data, it's your responsibility.

See this plunkr: http://plnkr.co/edit/b2R78FxvxdAWV0VHVywy?p=preview. Notice how you can drag and drop items to different list and the item is not removed from the drag list.

**Comment by Gab-Metzger-Melpia** [comment]
Got it, that's awesome! Thanks :)
