### ISSUE TITLE
Multiselect item feature in angular4 drag and drop

### ISSUE THREAD

**Issue by gravisrinivas** [ObaidUrRehman/ng2-drag-drop#92]
I am working on angular4 and i have a requirement whether I need to implement the drag and drop feature with multiple items selected. I have used ng2-drag-drop and dragula , but these allow to drag and drop a single item . Is there any way i implement drag and drop in angular4 with multi item select feature.

**Comment by Gab-Metzger-Melpia** [comment]
Is your requirement related to this issue #54 ?

**Comment by gravisrinivas** [comment]
yes

**Comment by ObaidUrRehman** [comment]
Closing as duplicate of #54
