### ISSUE TITLE
Add support for async dropScope function

### ISSUE THREAD

**Issue by akagr** [ObaidUrRehman/ng2-drag-drop#97]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] other

* **What is the current behavior?**
Right now, the `dropScope` has to be defined synchronously. If it's a function, it has to return true or false.

* **What is the expected behavior?**
I propose we allow the dropScope to be set to a function that returns an observable. That observable may then resolve to true or false. This would allow for scenarios, where say, we need to check with backend if the drop is allowed via http calls.

I'm willing to give developing this a try myself and PR it if it sounds good.

**Comment by ObaidUrRehman** [comment]
@akagr LGTM, the `dropScope` is already defined as `string | Array<string> | Function` so adding an `Observable` shouldn't be an issue.

Looking forward to your PR.
:+1:

**Comment by akagr** [comment]
@ObaidUrRehman Great thanks! Will try to get to it this weekend 😄

**Comment by ObaidUrRehman** [comment]
Added in v3.0.1
